<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ID</name>
   <tag></tag>
   <elementGuidId>a6ddf8aa-51ac-4c9b-b0f3-a0991b77303f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-0.text-left.btn.btn-link.text-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(),'ID')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0 text-left btn btn-link text-secondary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;top-header&quot;]/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;row col-sm-12 header-padding align-items-center&quot;]/div[@class=&quot;col-sm-9 top-header-nav&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;p-relative open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;nav-item pl-2 w-100&quot;]/button[@class=&quot;p-0 text-left btn btn-link text-secondary&quot;]</value>
   </webElementProperties>
</WebElementEntity>
